const PDFDocument = require('pdfkit-table');

class PdfReportService {
    /**
     * Build the standard header for the PDF report.
     * @param {PDFDocument} doc 
     * @param {string} title 
     * @param {Object} adminInfo 
     */
    static buildHeader(doc, title, adminInfo) {
        doc.fontSize(20).text('e-Fine SL - Admin Portal', { align: 'center' });
        doc.moveDown(0.5);
        doc.fontSize(16).text(title, { align: 'center' });
        doc.moveDown(1);
        
        doc.fontSize(10);
        doc.text(`Generated Date: ${new Date().toLocaleString()}`);
        if (adminInfo) {
            const adminName = adminInfo.name || 'Unknown Admin';
            const adminRole = adminInfo.role || 'Admin';
            doc.text(`Generated By: ${adminName} (${adminRole})`);
        }
        
        doc.moveDown(1);
        
        // Draw a line separator
        doc.moveTo(doc.x, doc.y)
           .lineTo(doc.page.width - doc.page.margins.right, doc.y)
           .stroke();
           
        doc.moveDown(1);
    }

    /**
     * Build the standard footer with page numbers.
     * @param {PDFDocument} doc 
     */
    static buildFooter(doc) {
        const pages = doc.bufferedPageRange();
        for (let i = 0; i < pages.count; i++) {
            doc.switchToPage(i);
            const pageNumber = i + 1;
            
            // Draw a line separator for the footer
            doc.moveTo(doc.page.margins.left, doc.page.height - 50)
               .lineTo(doc.page.width - doc.page.margins.right, doc.page.height - 50)
               .stroke();

            doc.fontSize(8)
               .text(
                   `Page ${pageNumber} of ${pages.count} - e-Fine SL Confidential`,
                   doc.page.margins.left,
                   doc.page.height - 40,
                   { align: 'center', width: doc.page.width - doc.page.margins.left - doc.page.margins.right }
               );
        }
    }

    /**
     * Create a new buffered PDF document.
     * @returns {PDFDocument}
     */
    static createDocument() {
        return new PDFDocument({
            margin: 50,
            size: 'A4',
            bufferPages: true // allow jumping back to add footer page numbers
        });
    }
}

module.exports = PdfReportService;
