const PDFDocument = require('pdfkit-table');

/**
 * Creative & Professional PDF Template Service for e-Fine SL Reports
 * Designed for executive-grade PDF reports across all administrative modules.
 */
class PdfReportService {
    // Brand Color Palette
    static COLORS = {
        PRIMARY_DARK: '#0F172A',    // Deep Navy Slate
        ACCENT_EMERALD: '#10B981',  // Emerald Green
        ACCENT_BLUE: '#2563EB',     // Royal Blue
        ACCENT_AMBER: '#F59E0B',    // Amber Gold
        ACCENT_RED: '#EF4444',      // Crimson Red
        TEXT_DARK: '#1E293B',       // Dark Charcoal
        TEXT_MUTED: '#64748B',      // Slate Grey
        BG_LIGHT: '#F8FAFC',        // Light Slate Tint
        BORDER_LIGHT: '#E2E8F0',    // Border Grey
        WHITE: '#FFFFFF',
    };

    /**
     * Create a new A4 buffered PDF Document
     */
    static createDocument(options = {}) {
        return new PDFDocument({
            margin: 40,
            size: 'A4',
            bufferPages: true,
            ...options
        });
    }

    /**
     * Build standard Brand Header with Title, Metadata Card, and Authority Badge
     * @param {PDFDocument} doc 
     * @param {Object} params - { title, category, adminInfo, reportId, dateRange }
     */
    static buildHeader(doc, { title, category = 'OFFICIAL AUDIT REPORT', adminInfo, reportId, dateRange }) {
        const pageWidth = doc.page.width;
        const margin = doc.page.margins.left;
        const contentWidth = pageWidth - (margin * 2);

        // 1. Top Brand Banner (Navy Slate)
        doc.rect(0, 0, pageWidth, 75).fill(this.COLORS.PRIMARY_DARK);

        // Emerald Accent Bar
        doc.rect(0, 75, pageWidth, 4).fill(this.COLORS.ACCENT_EMERALD);

        // 2. Banner Text Header
        doc.fillColor(this.COLORS.WHITE)
           .font('Helvetica-Bold')
           .fontSize(16)
           .text('e-Fine SL', margin, 18);

        doc.fillColor(this.COLORS.ACCENT_EMERALD)
           .font('Helvetica')
           .fontSize(9)
           .text('TRAFFIC MANAGEMENT AUTHORITY — SRI LANKA', margin, 38);

        // Right-aligned Category Badge on Banner
        doc.fillColor(this.COLORS.WHITE)
           .font('Helvetica-Bold')
           .fontSize(10)
           .text(category.toUpperCase(), margin, 24, { align: 'right', width: contentWidth });

        doc.fillColor(this.COLORS.BORDER_LIGHT)
           .font('Helvetica')
           .fontSize(8)
           .text(`Doc ID: ${reportId || 'RPT-' + Date.now().toString().slice(-6)}`, margin, 38, { align: 'right', width: contentWidth });

        // Move cursor below top banner
        doc.y = 95;

        // 3. Document Title Section
        doc.fillColor(this.COLORS.TEXT_DARK)
           .font('Helvetica-Bold')
           .fontSize(18)
           .text(title, margin, doc.y);

        doc.moveDown(0.3);

        // 4. Metadata Info Card Box (Rounded container)
        const cardY = doc.y;
        const cardHeight = 48;
        
        doc.roundedRect(margin, cardY, contentWidth, cardHeight, 6)
           .fillAndStroke(this.COLORS.BG_LIGHT, this.COLORS.BORDER_LIGHT);

        const textY = cardY + 10;
        const adminName = adminInfo?.name || 'Authorized Admin';
        const adminRole = (adminInfo?.role || 'SYSTEM_ADMIN').toUpperCase();
        const timestamp = new Date().toLocaleString('en-US', { timeZone: 'Asia/Colombo' }) + ' (SLST)';

        // Metadata Columns
        doc.fillColor(this.COLORS.TEXT_MUTED)
           .font('Helvetica')
           .fontSize(8.5);

        // Column 1: Generated By
        doc.text('GENERATED BY', margin + 12, textY);
        doc.fillColor(this.COLORS.TEXT_DARK)
           .font('Helvetica-Bold')
           .text(`${adminName} (${adminRole})`, margin + 12, textY + 12);

        // Column 2: Date / Time
        doc.fillColor(this.COLORS.TEXT_MUTED)
           .font('Helvetica')
           .text('GENERATED DATE & TIME', margin + 200, textY);
        doc.fillColor(this.COLORS.TEXT_DARK)
           .font('Helvetica-Bold')
           .text(timestamp, margin + 200, textY + 12);

        // Column 3: Date Range / Scope
        if (dateRange) {
            doc.fillColor(this.COLORS.TEXT_MUTED)
               .font('Helvetica')
               .text('REPORT PERIOD', margin + 380, textY);
            doc.fillColor(this.COLORS.TEXT_DARK)
               .font('Helvetica-Bold')
               .text(dateRange, margin + 380, textY + 12);
        }

        doc.y = cardY + cardHeight + 15;
    }

    /**
     * Render Section Title with a stylish Blue Accent Bar
     */
    static buildSectionHeader(doc, title) {
        const margin = doc.page.margins.left;
        const startY = doc.y;

        // Vertical Accent Bar
        doc.rect(margin, startY, 4, 16).fill(this.COLORS.ACCENT_BLUE);

        doc.fillColor(this.COLORS.TEXT_DARK)
           .font('Helvetica-Bold')
           .fontSize(12)
           .text(title, margin + 12, startY + 1);

        doc.moveDown(0.6);
    }

    /**
     * Render Responsive Executive KPI Summary Cards
     * @param {PDFDocument} doc 
     * @param {Array} cards - [{ label, value, subtext, color }]
     */
    static buildKPICards(doc, cards = []) {
        if (!cards || cards.length === 0) return;

        const margin = doc.page.margins.left;
        const pageWidth = doc.page.width;
        const contentWidth = pageWidth - (margin * 2);
        const cardCount = cards.length;
        const gap = 10;
        const cardWidth = (contentWidth - (gap * (cardCount - 1))) / cardCount;
        const cardHeight = 52;
        const startY = doc.y;

        cards.forEach((card, index) => {
            const cardX = margin + (index * (cardWidth + gap));
            const accentColor = card.color || this.COLORS.ACCENT_BLUE;

            // Card Background
            doc.roundedRect(cardX, startY, cardWidth, cardHeight, 6)
               .fillAndStroke(this.COLORS.BG_LIGHT, this.COLORS.BORDER_LIGHT);

            // Left Border Accent Strip
            doc.roundedRect(cardX, startY, 4, cardHeight, 2).fill(accentColor);

            // Label
            doc.fillColor(this.COLORS.TEXT_MUTED)
               .font('Helvetica-Bold')
               .fontSize(7.5)
               .text(card.label.toUpperCase(), cardX + 10, startY + 8, { width: cardWidth - 14 });

            // Main Value
            doc.fillColor(this.COLORS.TEXT_DARK)
               .font('Helvetica-Bold')
               .fontSize(13)
               .text(card.value.toString(), cardX + 10, startY + 20, { width: cardWidth - 14 });

            // Subtext if any
            if (card.subtext) {
                doc.fillColor(this.COLORS.TEXT_MUTED)
                   .font('Helvetica')
                   .fontSize(7)
                   .text(card.subtext, cardX + 10, startY + 36, { width: cardWidth - 14 });
            }
        });

        doc.y = startY + cardHeight + 15;
    }

    /**
     * Build Brand Footer with Page Numbers & Confidentiality Stamp
     */
    static buildFooter(doc) {
        const pages = doc.bufferedPageRange();
        const margin = doc.page.margins.left;
        const pageWidth = doc.page.width;
        const contentWidth = pageWidth - (margin * 2);
        const footerY = doc.page.height - 30;

        for (let i = 0; i < pages.count; i++) {
            doc.switchToPage(i);
            const origBottom = doc.page.margins.bottom;
            doc.page.margins.bottom = 0; // Prevent PDFKit auto-page-break when writing near bottom boundary

            // Footer Top Divider Line
            doc.moveTo(margin, footerY - 8)
               .lineTo(pageWidth - margin, footerY - 8)
               .strokeColor(this.COLORS.BORDER_LIGHT)
               .lineWidth(0.75)
               .stroke();

            // Confidentiality Note (Left)
            doc.fillColor(this.COLORS.TEXT_MUTED)
               .font('Helvetica')
               .fontSize(8)
               .text(
                   'CONFIDENTIAL — e-Fine SL Traffic Authority | Official Document',
                   margin,
                   footerY,
                   { width: contentWidth / 2, lineBreak: false }
               );

            // Page Numbering (Right)
            doc.fillColor(this.COLORS.TEXT_MUTED)
               .font('Helvetica-Bold')
               .fontSize(8)
               .text(
                   `Page ${i + 1} of ${pages.count}`,
                   margin + (contentWidth / 2),
                   footerY,
                   { align: 'right', width: contentWidth / 2, lineBreak: false }
               );

            doc.page.margins.bottom = origBottom;
        }
    }

    /**
     * Build Official Single-Page e-Fine SL Digital Fine Receipt with Embedded QR Verification
     */
    static buildReceipt(doc, { fine, driver, qrBuffer }) {
        const pageWidth = doc.page.width;
        const margin = doc.page.margins.left;
        const contentWidth = pageWidth - (margin * 2);

        // 1. Top Brand Banner
        doc.rect(0, 0, pageWidth, 75).fill(this.COLORS.PRIMARY_DARK);
        doc.rect(0, 75, pageWidth, 4).fill(this.COLORS.ACCENT_EMERALD);

        doc.fillColor(this.COLORS.WHITE)
           .font('Helvetica-Bold')
           .fontSize(16)
           .text('e-Fine SL', margin, 18);

        doc.fillColor(this.COLORS.ACCENT_EMERALD)
           .font('Helvetica')
           .fontSize(9)
           .text('TRAFFIC MANAGEMENT AUTHORITY — SRI LANKA', margin, 38);

        doc.fillColor(this.COLORS.WHITE)
           .font('Helvetica-Bold')
           .fontSize(10)
           .text('DIGITAL FINE RECEIPT', margin, 24, { align: 'right', width: contentWidth });

        const fineIdShort = (fine._id || '').toString().slice(-8).toUpperCase();
        doc.fillColor(this.COLORS.BORDER_LIGHT)
           .font('Helvetica')
           .fontSize(8)
           .text(`Ref: SL-FINE-${fineIdShort}`, margin, 38, { align: 'right', width: contentWidth });

        doc.y = 95;

        // 2. Receipt Status Header Box
        const isPaid = String(fine.status).toUpperCase() === 'PAID';
        const statusBg = isPaid ? '#ECFDF5' : '#FEF2F2';
        const statusBorder = isPaid ? '#10B981' : '#EF4444';
        const statusText = isPaid ? '#047857' : '#B91C1C';
        const statusLabel = isPaid ? 'PAID / CLEARED' : 'UNPAID / PENDING';

        doc.roundedRect(margin, doc.y, contentWidth, 50, 6)
           .fillAndStroke(statusBg, statusBorder);

        const cardY = doc.y + 10;

        doc.fillColor(statusText)
           .font('Helvetica-Bold')
           .fontSize(12)
           .text(statusLabel, margin + 14, cardY);

        doc.fillColor(this.COLORS.TEXT_MUTED)
           .font('Helvetica')
           .fontSize(8.5)
           .text(`FINE AMOUNT`, margin + 300, cardY);

        const formattedAmount = `LKR ${Number(fine.amount || 0).toLocaleString('en-LK', { minimumFractionDigits: 2 })}`;
        doc.fillColor(this.COLORS.PRIMARY_DARK)
           .font('Helvetica-Bold')
           .fontSize(14)
           .text(formattedAmount, margin + 300, cardY + 12);

        doc.y = cardY + 45;

        // 3. Section 1: Offense & Fine Details
        this.buildSectionHeader(doc, 'Fine & Offense Information');

        const detailsY = doc.y;
        const colWidth = (contentWidth - 20) / 2;

        doc.roundedRect(margin, detailsY, contentWidth, 125, 6)
           .fillAndStroke(this.COLORS.BG_LIGHT, this.COLORS.BORDER_LIGHT);

        const row1 = detailsY + 12;
        const row2 = detailsY + 48;
        const row3 = detailsY + 84;

        // Col 1 Details
        doc.fillColor(this.COLORS.TEXT_MUTED).font('Helvetica').fontSize(8).text('OFFENSE TYPE', margin + 12, row1);
        doc.fillColor(this.COLORS.TEXT_DARK).font('Helvetica-Bold').fontSize(10).text(fine.offenseName || 'Traffic Offense', margin + 12, row1 + 10);

        doc.fillColor(this.COLORS.TEXT_MUTED).font('Helvetica').fontSize(8).text('VEHICLE REGISTRATION NO', margin + 12, row2);
        doc.fillColor(this.COLORS.TEXT_DARK).font('Helvetica-Bold').fontSize(10).text((fine.vehicleNumber || 'N/A').toUpperCase(), margin + 12, row2 + 10);

        doc.fillColor(this.COLORS.TEXT_MUTED).font('Helvetica').fontSize(8).text('LOCATION / PLACE', margin + 12, row3);
        doc.fillColor(this.COLORS.TEXT_DARK).font('Helvetica-Bold').fontSize(9).text(fine.place || 'Sri Lanka', margin + 12, row3 + 10, { width: colWidth - 10 });

        // Col 2 Details
        doc.fillColor(this.COLORS.TEXT_MUTED).font('Helvetica').fontSize(8).text('DATE & TIME', margin + colWidth + 20, row1);
        const fineDate = fine.date ? new Date(fine.date).toLocaleString('en-US', { timeZone: 'Asia/Colombo' }) : 'N/A';
        doc.fillColor(this.COLORS.TEXT_DARK).font('Helvetica-Bold').fontSize(9.5).text(fineDate, margin + colWidth + 20, row1 + 10);

        doc.fillColor(this.COLORS.TEXT_MUTED).font('Helvetica').fontSize(8).text('ISSUING POLICE OFFICER BADGE', margin + colWidth + 20, row2);
        doc.fillColor(this.COLORS.TEXT_DARK).font('Helvetica-Bold').fontSize(10).text(fine.policeOfficerId || 'N/A', margin + colWidth + 20, row2 + 10);

        doc.fillColor(this.COLORS.TEXT_MUTED).font('Helvetica').fontSize(8).text('DEMERIT POINTS DEDUCTED', margin + colWidth + 20, row3);
        const ptsDeducted = fine.demeritPoints || 0;
        doc.fillColor(ptsDeducted > 0 ? this.COLORS.ACCENT_RED : this.COLORS.TEXT_DARK)
           .font('Helvetica-Bold')
           .fontSize(10)
           .text(`-${ptsDeducted} Points`, margin + colWidth + 20, row3 + 10);

        doc.y = detailsY + 135 + 10;

        // 4. Section 2: Driver & Demerit Rating Status
        this.buildSectionHeader(doc, 'Driver Identification & Rating');

        const driverY = doc.y;
        doc.roundedRect(margin, driverY, contentWidth, 75, 6)
           .fillAndStroke(this.COLORS.BG_LIGHT, this.COLORS.BORDER_LIGHT);

        const dRow = driverY + 12;

        doc.fillColor(this.COLORS.TEXT_MUTED).font('Helvetica').fontSize(8).text('DRIVER NAME', margin + 12, dRow);
        doc.fillColor(this.COLORS.TEXT_DARK).font('Helvetica-Bold').fontSize(10).text(driver?.name || 'Registered Driver', margin + 12, dRow + 10);

        doc.fillColor(this.COLORS.TEXT_MUTED).font('Helvetica').fontSize(8).text('DRIVING LICENSE NUMBER', margin + 12, dRow + 36);
        doc.fillColor(this.COLORS.TEXT_DARK).font('Helvetica-Bold').fontSize(10).text((fine.licenseNumber || 'N/A').toUpperCase(), margin + 12, dRow + 46);

        doc.fillColor(this.COLORS.TEXT_MUTED).font('Helvetica').fontSize(8).text('CURRENT LICENSE STATUS', margin + colWidth + 20, dRow);
        const licStatus = (driver?.licenseStatus || 'ACTIVE').toUpperCase();
        doc.fillColor(licStatus === 'SUSPENDED' ? this.COLORS.ACCENT_RED : this.COLORS.ACCENT_EMERALD)
           .font('Helvetica-Bold')
           .fontSize(10)
           .text(licStatus, margin + colWidth + 20, dRow + 10);

        doc.fillColor(this.COLORS.TEXT_MUTED).font('Helvetica').fontSize(8).text('REMAINING DEMERIT POINTS', margin + colWidth + 20, dRow + 36);
        const remPts = driver?.demeritPoints !== undefined ? driver.demeritPoints : 24;
        doc.fillColor(this.COLORS.TEXT_DARK)
           .font('Helvetica-Bold')
           .fontSize(10)
           .text(`${remPts} / 24 Points (${driver?.demeritLevel || 'FAIR'})`, margin + colWidth + 20, dRow + 46);

        doc.y = driverY + 85 + 10;

        // 5. Verification QR Code Section
        if (qrBuffer) {
            const qrY = doc.y;
            doc.roundedRect(margin, qrY, contentWidth, 90, 6)
               .fillAndStroke('#F1F5F9', this.COLORS.BORDER_LIGHT);

            // Embed QR Code Image
            doc.image(qrBuffer, margin + 12, qrY + 10, { width: 70, height: 70 });

            doc.fillColor(this.COLORS.PRIMARY_DARK)
               .font('Helvetica-Bold')
               .fontSize(10)
               .text('Official QR Verification Stamp', margin + 95, qrY + 16);

            doc.fillColor(this.COLORS.TEXT_MUTED)
               .font('Helvetica')
               .fontSize(8)
               .text('Scan this QR code using the e-Fine SL Mobile App or law enforcement scanner to verify the authenticity of this digital fine receipt.', margin + 95, qrY + 32, { width: contentWidth - 110 });

            doc.fillColor(this.COLORS.ACCENT_BLUE)
               .font('Helvetica-Bold')
               .fontSize(8)
               .text('VERIFIED DIGITAL DOCUMENT — TRAFFIC POLICE SRI LANKA', margin + 95, qrY + 62);

            doc.y = qrY + 100;
        }

        // 6. Footer
        this.buildFooter(doc);
    }
}

module.exports = PdfReportService;
