const PDFDocument = require('pdfkit-table');

/**
 * Creative & Professional PDF Template Service for e-Fine SL Reports
 * Designed for executive-grade PDF reports across all administrative modules.
 */
class PdfReportService {
    // Brand Color Palette
    static COLORS = {
        PRIMARY_DARK: '#0F172A',    // Deep Navy Slate
        ACCENT_EMERALD: '#10B981',  // Emerald Green
        ACCENT_BLUE: '#2563EB',     // Royal Blue
        ACCENT_AMBER: '#F59E0B',    // Amber Gold
        ACCENT_RED: '#EF4444',      // Crimson Red
        TEXT_DARK: '#1E293B',       // Dark Charcoal
        TEXT_MUTED: '#64748B',      // Slate Grey
        BG_LIGHT: '#F8FAFC',        // Light Slate Tint
        BORDER_LIGHT: '#E2E8F0',    // Border Grey
        WHITE: '#FFFFFF',
    };

    /**
     * Create a new A4 buffered PDF Document
     */
    static createDocument(options = {}) {
        return new PDFDocument({
            margin: 40,
            size: 'A4',
            bufferPages: true,
            ...options
        });
    }

    /**
     * Build standard Brand Header with Title, Metadata Card, and Authority Badge
     * @param {PDFDocument} doc 
     * @param {Object} params - { title, category, adminInfo, reportId, dateRange }
     */
    static buildHeader(doc, { title, category = 'OFFICIAL AUDIT REPORT', adminInfo, reportId, dateRange }) {
        const pageWidth = doc.page.width;
        const margin = doc.page.margins.left;
        const contentWidth = pageWidth - (margin * 2);

        // 1. Top Brand Banner (Navy Slate)
        doc.rect(0, 0, pageWidth, 75).fill(this.COLORS.PRIMARY_DARK);

        // Emerald Accent Bar
        doc.rect(0, 75, pageWidth, 4).fill(this.COLORS.ACCENT_EMERALD);

        // 2. Banner Text Header
        doc.fillColor(this.COLORS.WHITE)
           .font('Helvetica-Bold')
           .fontSize(16)
           .text('e-Fine SL', margin, 18);

        doc.fillColor(this.COLORS.ACCENT_EMERALD)
           .font('Helvetica')
           .fontSize(9)
           .text('TRAFFIC MANAGEMENT AUTHORITY — SRI LANKA', margin, 38);

        // Right-aligned Category Badge on Banner
        doc.fillColor(this.COLORS.WHITE)
           .font('Helvetica-Bold')
           .fontSize(10)
           .text(category.toUpperCase(), margin, 24, { align: 'right', width: contentWidth });

        doc.fillColor(this.COLORS.BORDER_LIGHT)
           .font('Helvetica')
           .fontSize(8)
           .text(`Doc ID: ${reportId || 'RPT-' + Date.now().toString().slice(-6)}`, margin, 38, { align: 'right', width: contentWidth });

        // Move cursor below top banner
        doc.y = 95;

        // 3. Document Title Section
        doc.fillColor(this.COLORS.TEXT_DARK)
           .font('Helvetica-Bold')
           .fontSize(18)
           .text(title, margin, doc.y);

        doc.moveDown(0.3);

        // 4. Metadata Info Card Box (Rounded container)
        const cardY = doc.y;
        const cardHeight = 48;
        
        doc.roundedRect(margin, cardY, contentWidth, cardHeight, 6)
           .fillAndStroke(this.COLORS.BG_LIGHT, this.COLORS.BORDER_LIGHT);

        const textY = cardY + 10;
        const adminName = adminInfo?.name || 'Authorized Admin';
        const adminRole = (adminInfo?.role || 'SYSTEM_ADMIN').toUpperCase();
        const timestamp = new Date().toLocaleString('en-US', { timeZone: 'Asia/Colombo' }) + ' (SLST)';

        // Metadata Columns
        doc.fillColor(this.COLORS.TEXT_MUTED)
           .font('Helvetica')
           .fontSize(8.5);

        // Column 1: Generated By
        doc.text('GENERATED BY', margin + 12, textY);
        doc.fillColor(this.COLORS.TEXT_DARK)
           .font('Helvetica-Bold')
           .text(`${adminName} (${adminRole})`, margin + 12, textY + 12);

        // Column 2: Date / Time
        doc.fillColor(this.COLORS.TEXT_MUTED)
           .font('Helvetica')
           .text('GENERATED DATE & TIME', margin + 200, textY);
        doc.fillColor(this.COLORS.TEXT_DARK)
           .font('Helvetica-Bold')
           .text(timestamp, margin + 200, textY + 12);

        // Column 3: Date Range / Scope
        if (dateRange) {
            doc.fillColor(this.COLORS.TEXT_MUTED)
               .font('Helvetica')
               .text('REPORT PERIOD', margin + 380, textY);
            doc.fillColor(this.COLORS.TEXT_DARK)
               .font('Helvetica-Bold')
               .text(dateRange, margin + 380, textY + 12);
        }

        doc.y = cardY + cardHeight + 15;
    }

    /**
     * Render Section Title with a stylish Blue Accent Bar
     */
    static buildSectionHeader(doc, title) {
        const margin = doc.page.margins.left;
        const startY = doc.y;

        // Vertical Accent Bar
        doc.rect(margin, startY, 4, 16).fill(this.COLORS.ACCENT_BLUE);

        doc.fillColor(this.COLORS.TEXT_DARK)
           .font('Helvetica-Bold')
           .fontSize(12)
           .text(title, margin + 12, startY + 1);

        doc.moveDown(0.6);
    }

    /**
     * Render Responsive Executive KPI Summary Cards
     * @param {PDFDocument} doc 
     * @param {Array} cards - [{ label, value, subtext, color }]
     */
    static buildKPICards(doc, cards = []) {
        if (!cards || cards.length === 0) return;

        const margin = doc.page.margins.left;
        const pageWidth = doc.page.width;
        const contentWidth = pageWidth - (margin * 2);
        const cardCount = cards.length;
        const gap = 10;
        const cardWidth = (contentWidth - (gap * (cardCount - 1))) / cardCount;
        const cardHeight = 52;
        const startY = doc.y;

        cards.forEach((card, index) => {
            const cardX = margin + (index * (cardWidth + gap));
            const accentColor = card.color || this.COLORS.ACCENT_BLUE;

            // Card Background
            doc.roundedRect(cardX, startY, cardWidth, cardHeight, 6)
               .fillAndStroke(this.COLORS.BG_LIGHT, this.COLORS.BORDER_LIGHT);

            // Left Border Accent Strip
            doc.roundedRect(cardX, startY, 4, cardHeight, 2).fill(accentColor);

            // Label
            doc.fillColor(this.COLORS.TEXT_MUTED)
               .font('Helvetica-Bold')
               .fontSize(7.5)
               .text(card.label.toUpperCase(), cardX + 10, startY + 8, { width: cardWidth - 14 });

            // Main Value
            doc.fillColor(this.COLORS.TEXT_DARK)
               .font('Helvetica-Bold')
               .fontSize(13)
               .text(card.value.toString(), cardX + 10, startY + 20, { width: cardWidth - 14 });

            // Subtext if any
            if (card.subtext) {
                doc.fillColor(this.COLORS.TEXT_MUTED)
                   .font('Helvetica')
                   .fontSize(7)
                   .text(card.subtext, cardX + 10, startY + 36, { width: cardWidth - 14 });
            }
        });

        doc.y = startY + cardHeight + 15;
    }

    /**
     * Build Brand Footer with Page Numbers & Confidentiality Stamp
     */
    static buildFooter(doc) {
        const pages = doc.bufferedPageRange();
        const margin = doc.page.margins.left;
        const pageWidth = doc.page.width;
        const contentWidth = pageWidth - (margin * 2);
        const footerY = doc.page.height - 35;

        for (let i = 0; i < pages.count; i++) {
            doc.switchToPage(i);

            // Footer Top Divider Line
            doc.moveTo(margin, footerY - 10)
               .lineTo(pageWidth - margin, footerY - 10)
               .strokeColor(this.COLORS.BORDER_LIGHT)
               .lineWidth(0.75)
               .stroke();

            // Confidentiality Note (Left)
            doc.fillColor(this.COLORS.TEXT_MUTED)
               .font('Helvetica')
               .fontSize(8)
               .text(
                   'CONFIDENTIAL — e-Fine SL Traffic Authority | Official Document',
                   margin,
                   footerY,
                   { width: contentWidth / 2 }
               );

            // Page Numbering (Right)
            doc.fillColor(this.COLORS.TEXT_MUTED)
               .font('Helvetica-Bold')
               .fontSize(8)
               .text(
                   `Page ${i + 1} of ${pages.count}`,
                   margin + (contentWidth / 2),
                   footerY,
                   { align: 'right', width: contentWidth / 2 }
               );
        }
    }
}

module.exports = PdfReportService;
